(define-abbrev-table 'mizar-mode-abbrev-table '(
    ("contra" "contradiction" nil 0)
    ("refl" "reflexivity" nil 0)
    ("hn" "hence" nil 0)
    ("hl" "holds" nil 0)
    ("pf" "proof" nil 0)
    ("cons" "consider" nil 0)
    ("pc" "per cases" nil 0)
    ("coh" "coherence" nil 0)
    ("fs" "FinSequence" nil 0)
    ("hb" "hereby" nil 0)
    ("sct" "such that" nil 0)
    ("tco" "the carrier of" nil 0)
    ("reg" "regular" nil 0)
    ("ts" "thesis" nil 0)
    ("rec" "reconsider" nil 0)
    ("eq"  "equals" nil 0)
    ("tm"  "theorem" nil 0)
    ("el" "Element" nil 0)
    ("supp" "suppose" nil 0)
    ("rv"   "reserve" nil 0)
    ("corr" "correctness" nil 0)
    ("coh" "coherence" nil 0)
    ("bei" "being" nil 0)
    ("ass" "assume" nil 0)
    ("monot" "monotone" nil 0)
    ("uniq" "uniqueness" nil 0)
    ("df"  "definition" nil 0)
    ("cl" "cluster" nil 0)
    ("exi" "existence" nil 0)
    ("redef" "redefine" nil 0)
    ("carr" "carrier" nil 0)
    ("imp"  "implies" nil 0)
    ("e" "end;" nil 0)
    ))
